# Generated by Django 3.1.4 on 2021-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210104_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='subject_title',
        ),
    ]
