# Generated by Django 3.1.4 on 2021-01-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210104_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='title',
            new_name='name_surname',
        ),
    ]
