# Generated by Django 3.1.4 on 2021-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210104_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
