# Generated by Django 3.1.4 on 2021-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sale',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
