# Generated by Django 3.1.4 on 2021-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210113_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
