# Generated by Django 3.1.4 on 2021-03-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
    ]
