# Generated by Django 3.1.4 on 2021-03-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210324_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='modified',
        ),
    ]
