# Generated by Django 3.1.4 on 2021-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
